Update cicd-script.yml

diff --git a/.github/workflows/cicd-script.yml b/.github/workflows/cicd-script.yml
--- a/.github/workflows/cicd-script.yml
+++ b/.github/workflows/cicd-script.yml
@@ -72,14 +72,18 @@ jobs:
       - name: Build with Gradle
         run: ./gradlew clean build
 
+      # DockerHub에 로그인
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
+      # Docker image 빌드
       - name: Build Docker
         run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/freshmate .
+
+      # DuckerHub에 Push
       - name: Push Docker
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/freshmate:latest
         
@@ -87,64 +91,88 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
-      - name: Set target IP
-        run: |
-          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.FRESHMATE_IP }}/env")
-          echo $STATUS
-          if [ $STATUS = 200 ]; then
-            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.FRESHMATE_IP }}/env")
-          else
-            CURRENT_UPSTREAM=green
-          fi
-          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
-          if [ $CURRENT_UPSTREAM = blue ]; then
-            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
-          elif [ $CURRENT_UPSTREAM = green ]; then
-            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
-            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
-            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
-          else
-            echo "error"
-            exit 1
-          fi
-          
-      - name: Docker compose
+      # deploy.sh 파일 서버로 전달하기(복사 후 붙여넣기)
+      - name: Send deploy.sh
+        uses: appleboy/scp-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.FRESHMATE_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          port: 22
+          source: "./deploy.sh"
+          target: "/home/ubuntu/"
+
+      # 도커 허브에서 jar파일 및 pull후에 컴포즈 up
+      - name: Deploy to Dev
         uses: appleboy/ssh-action@master
         with:
           username: ubuntu
           host: ${{ secrets.FRESHMATE_IP }}
           key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
           script: |
             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/freshmate:latest
-            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
-      
-      - name: Check deploy server URL
-        uses: jtalk/url-health-check-action@v3
-        with:
-          url: http://${{ secrets.FRESHMATE_IP }}:${{env.STOPPED_PORT}}/env
-          max-attempts: 5
-          retry-delay: 10s
-
-      - name: Change nginx upstream
-        uses: appleboy/ssh-action@master
-        with:
-          username: ubuntu
-          host: ${{ secrets.FRESHMATE_IP }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
-          script: |
-            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
-
-      - name: Stop current server
-        uses: appleboy/ssh-action@master
-        with:
-          username: ubuntu
-          host: ${{ secrets.FRESHMATE_IP }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script_stop: true
-          script: |
-            sudo docker stop ${{env.CURRENT_UPSTREAM}}
-            sudo docker rm ${{env.CURRENT_UPSTREAM}}
+            chmod 777 ./deploy.sh
+            ./deploy.sh
+            docker image prune -f
+    
+#      - name: Set target IP
+#        run: |
+#          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.FRESHMATE_IP }}/env")
+#          echo $STATUS
+#          if [ $STATUS = 200 ]; then
+#            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.FRESHMATE_IP }}/env")
+#          else
+#            CURRENT_UPSTREAM=green
+#          fi
+#          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+#          if [ $CURRENT_UPSTREAM = blue ]; then
+#            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+#            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+#            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+#          elif [ $CURRENT_UPSTREAM = green ]; then
+#            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+#            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+#            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+#          else
+#            echo "error"
+#            exit 1
+#          fi
+#          
+#      - name: Docker compose
+#        uses: appleboy/ssh-action@master
+#        with:
+#          username: ubuntu
+#          host: ${{ secrets.FRESHMATE_IP }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script_stop: true
+#          script: |
+#            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/freshmate:latest
+#            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+#      
+#      - name: Check deploy server URL
+#        uses: jtalk/url-health-check-action@v3
+#        with:
+#          url: http://${{ secrets.FRESHMATE_IP }}:${{env.STOPPED_PORT}}/env
+#          max-attempts: 5
+#          retry-delay: 10s
+#
+#      - name: Change nginx upstream
+#        uses: appleboy/ssh-action@master
+#        with:
+#          username: ubuntu
+#          host: ${{ secrets.FRESHMATE_IP }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script_stop: true
+#          script: |
+#            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+#
+#      - name: Stop current server
+#        uses: appleboy/ssh-action@master
+#        with:
+#          username: ubuntu
+#          host: ${{ secrets.FRESHMATE_IP }}
+#          key: ${{ secrets.EC2_SSH_KEY }}
+#          script_stop: true
+#          script: |
+#            sudo docker stop ${{env.CURRENT_UPSTREAM}}
+#            sudo docker rm ${{env.CURRENT_UPSTREAM}}
